<?php

/**
 * Implements hook_menu().
 */
function zeddigital_menu() {
  return array(
    'node/%node/delete_programmatically' => array(
      'title' => t('Delete'),
      'page callback' => 'redirect_to_node_delete',
      'access callback' => 'zeddigital_node_delete_access',
      'access arguments' => array($node),
      'callback arguments' => array($node),
      'type' => MENU_LOCAL_TASK,
      'weight' => 3,
    ),
  );
}

/**
 * Check if the user can delete the current node.
 */
function zeddigital_node_delete_access() {
  global $user;
  $node = node_load(arg(1));
  return node_access('delete', $node, $user);
}

/**
 * Helper function for menu_local_task.
 */
function redirect_to_node_delete() {
  if (arg(0) == 'node' && arg(1) && is_numeric(arg(1))) {
    drupal_goto('node/' . arg(1) . '/delete');
  }
}

/**
 * Implements hook_form_alter().
 */
function zeddigital_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'media_plan_node_form':
      unset($form['title']);
      break;
  }
}

/**
 * Implements hook_node_insert().
 */
function zeddigital_node_insert($node) {
  if ($node->type == 'media_plan') {
    $title = $node->nid;
    $title .= '_' . $node->field_brand[LANGUAGE_NONE][0]['name'];
    $title = str_replace(' ', '-', $title);
    db_update('node')
      ->fields(array('title' => $title,))
      ->condition('nid', $node->nid)
      ->execute();
    db_update('node_revision')
      ->fields(array('title' => $title,))
      ->condition('nid', $node->nid)
      ->execute();
  }
}
